### ISSUE TITLE
不多说

### ISSUE THREAD

**Issue by lest-day** [HelloOSMe/Py-crawler#4]
首先，你程序崩了，
然后，你程序被杀毒软件报木马了
这会导致什么你自己清楚

**Comment by HelloOSMe** [comment]
那是windows自己的问题，不行你可以看源码。

**Comment by HelloOSMe** [comment]
那是查毒软件自己的问题，不行你可以看源码。试着启动main.exe呢？毕竟vb6误报不在少数。
而且，`无法识别!=木马`

还有就是程序错误信息发过来。

@lest-day
